on:
  pull_request:
  push:
    branches: [master]
name: Build and Deploy to gh-pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: build
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Build
        run: npm run build

      - name: Create Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./dist/static"
  pages-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v2

